### ISSUE TITLE
Database tab - Schema Mapping should alter expanded table list

### ISSUE THREAD

**Issue by naxels** [Wisser/Jailer#92]
### Is your feature request related to a problem? Please describe.

When I open the Relational Data Browser using a PostgreSQL database selected,
for which I've updated the Schema Mapping to not use public but another one called data.

Now when I switch to the Database tab, the public schema is fully expanded to the table list.

### Describe the solution you'd like

It would be nice if either:

- The Schema Mapping schema is expanded by default (data in my case)
- The expanded schema's include both public and the Schema Mapping schema

### Describe alternatives you've considered

It's easy to just open up the other schema, so no big deal.

### Additional context

Interestingly: the "Open Table" button on the Database tab, does show the public and Schema Mapping schema selected.

Again, thank you for your continuous development and support!

**Comment by naxels** [comment]
Hi Wisser,

I just tested this, it's working when I'm using the demo databases and then switch to a different Schema Mapping (while on the Database tab, the table list reloads and the schema is expanded as expected)

However with my PostgreSQL database it won't (and no error on CLI either)

I tried:
- Click Ok on the current schema
- Change the schema to something else, then come back and change again to the one I want

I tried it with an Oracle database (large one) and it works..


Maybe.. the issue with the PostgreSQL database is that when I load the GUI / select connection etc,
the other than public schema is already selected in the Schema Mapping"

while the Demo & Oracle database, I change the default after the GUI loads.

(trying to remember how I changed the default schema in Jailer during setup)

**Comment by Wisser** [comment]
The configuration for PostgreSQL was incomplete, so the current schema could not be determined correctly.
If you replace the file "jailer.xml" with this one, it should work.

**Comment by naxels** [comment]
I tried replacing the jailer.xml file, and tried on 2 PostgreSQL databases:

1. This one defaults to public schema and works perfect
2. This database shows me default schema sfdc and doesn't work.

I checked the query in the xml (from the diff in Github) and that does work / gives me same result.

I did a little more digging into a possible reason and I discovered that on the 2nd database,
my user only has access rights to the sfdc schema, not public.

This is showing in Jailer in a correct way:
<img width="352" alt="image" src="https://user-images.githubusercontent.com/3195443/183241473-88661ae2-0d45-4e89-90f7-4ad9bb2d4b82.png">

However for some reason the Database tab always kicks back to expanding the public schema by default / upon switching schema.

**Comment by Wisser** [comment]
Are you sure that when you log into the database "sfdc" that then:
`Select current_schema()`
results in "sfdc"?

Because then this schema should be opened initially.

In which way has the schema "sfdc" been set as default schema? I am not a PostgreSQL specialist. I have tried a few things and now I am testing the handling of changed default schema by setting the default schema via JDBC parameter "currentSchema". Maybe there are other options with other consequences?

**Comment by naxels** [comment]
Hi Wisser,

In DataGrip, the default IDE I use for all simple database querying, this is the case, yes:
<img width="170" alt="image" src="https://user-images.githubusercontent.com/3195443/183670236-4b7b2a70-d2a7-45e1-8e1d-7b2915e56992.png">

However... I don't know the trickery that DataGrip does on the backend to make this work.

But judging how Jailer also says .... instead of sfdc (see previous post screenshot)
I would assume that this is somehow the case.

I will look into "default schema" some more and update this comment.

**Comment by Wisser** [comment]
I have now extended the mapping dialog so that another schema can always be assigned to the default schema. It is so that in this dialog actually only schemas are listed which are relevant in the data model (for which there are tables in the data model). For the SQL console, the mapping is actually irrelevant. The only exception now is that the schema assigned to the default schema is opened initially.

Could you test this with the 12.5.3.20 (attached in the other issue)? Thank you very much.

(Jailer itself does not know any mechanism to set the default scheme. For PostgreSQL you can define it in the JDBC URL:
`jdbc:postgresql://localhost:5432/postgres?currentSchema=sfdc`
)

**Comment by naxels** [comment]
I tested 12.5.3.20 and in the Schema Mapping I now have a default of public and when I switch it to sfdc, it works as expected :)

When adding the ?currentSchema=sfdc to the JDBC url, it also works as expected, the Schema Mapping / Database tab now show sfdc as default :)
