### ISSUE TITLE
Some panels cannot display non ASCII characters correctly

### ISSUE THREAD

**Issue by acn-leoli** [Wisser/Jailer#98]
### Description of the Issue
If the database record contains non ASCII characters (e.g. Chinese, in my case), some panels cannot display the characters correctly (but some can).

![image](https://user-images.githubusercontent.com/68094295/197723285-66a00d43-cccb-42c7-91bd-10941f606d60.png)

### Database
MySQL 8 in my case.

### Jailer
Jailer 12.7.4

**Comment by Wisser** [comment]
Thanks for the report.

There was a problem with the way the font for the table content is determined. This is fixed now.

Based on release 12.7.4 you can find a patch attached. Please replace the file "jailer.jar" with the one in the attachment and test it in advance. Thanks a lot.
(I had to put the file into a zip archive because github does not allow jar files as attachments)

[jailer_12.7.4.6.zip](https://github.com/Wisser/Jailer/files/9859545/jailer_12.7.4.6.zip)

**Comment by acn-leoli** [comment]
Tried the patch and so far so good!

Thanks for your quick response!
